# Generated by Django 5.1.2 on 2024-11-14 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_rename_nombre_indicador_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='revision',
            field=models.CharField(default='01/2021', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='texto_revision',
            field=models.CharField(default='Texto de revisio', max_length=100),
            preserve_default=False,
        ),
    ]
