# Generated by Django 5.1.2 on 2024-11-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_indicador_fecha_fin_indicador_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='dia',
            field=models.CharField(default='dia', max_length=15),
            preserve_default=False,
        ),
    ]
