# Generated by Django 5.1.2 on 2024-11-20 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_indicador_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
