# Generated by Django 5.1.2 on 2024-11-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_indicador_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='equipo_parado',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
    ]
