# Generated by Django 5.1.2 on 2024-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_indicador_equipo_parado'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='estatus',
            field=models.CharField(default='Programado', max_length=30),
        ),
    ]
