# Generated by Django 5.1.2 on 2024-11-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_indicador_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='indicador',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completado', 'Completado')], default='Programado', max_length=30),
        ),
    ]
