# Generated by Django 5.1.2 on 2024-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_remove_indicador_fecha_alter_indicador_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='estatus',
            field=models.CharField(choices=[('programado', 'Programado'), ('entregado', 'Entregado'), ('no_entregado', 'No entregado')], default='Programado', max_length=30),
        ),
    ]
