# Generated by Django 5.1.2 on 2024-11-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0009_alter_indicador_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='estatus',
        ),
        migrations.AddField(
            model_name='indicador',
            name='estatus_mantenimiento',
            field=models.CharField(choices=[('Programado', 'Programado'), ('Tomado', 'Tomado'), ('No tomado', 'No tomado')], default='Programado', max_length=30),
        ),
        migrations.AddField(
            model_name='indicador',
            name='estatus_operaciones',
            field=models.CharField(choices=[('Programado', 'Programado'), ('Entregado', 'Entregado'), ('No entregado', 'No entregado')], default='Programado', max_length=30),
        ),
    ]
