# Generated by Django 5.1.2 on 2024-11-28 21:01

import equipos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0010_remove_indicador_estatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=7, validators=[equipos.models.week_test])),
                ('s_date', models.DateField()),
                ('f_date', models.DateField()),
                ('ot_prev', models.IntegerField()),
                ('ot_corr', models.IntegerField()),
                ('ot_prev_exe', models.IntegerField()),
                ('ot_corr_exe', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Semana',
                'verbose_name_plural': 'Semanas',
            },
        ),
        migrations.AlterField(
            model_name='indicador',
            name='revision',
            field=models.CharField(max_length=50, validators=[equipos.models.week_test]),
        ),
    ]
