# Generated by Django 5.1.2 on 2024-11-28 21:03

import equipos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0011_revision_alter_indicador_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='revision',
            field=models.CharField(max_length=7, validators=[equipos.models.week_test]),
        ),
    ]
