# Generated by Django 5.1.2 on 2024-11-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0012_alter_indicador_revision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
    ]
