# Generated by Django 5.1.2 on 2024-12-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0013_alter_indicador_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='ot_corr',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='ot_corr_exe',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='ot_prev',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='ot_prev_exe',
        ),
    ]
