# Generated by Django 5.1.2 on 2025-01-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0015_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
